### ISSUE TITLE
Gracefully decline to connect to versions < 12

### ISSUE THREAD

**Issue by jamesrusso** [sqlanywhere/sqlany-django#1]
I have an application which uses SQLAnywhere 10. I am getting error on connection due to:

cursor.execute("SET OPTION PUBLIC.reserved_keywords='LIMIT'")

However, after that error I am able to interact with the cursor without issue.

**Comment by gperrow-SAP** [comment]
With version 1.6 (uploaded today), this issue should go away unless you are using Django 1.1. With Django 1.2 or later, we now rewrite queries using LIMIT so that they use TOP instead, and so we don't need to set the reserved_keywords option at all.
