### ISSUE TITLE
End of extended support for Django 1.7.10 in December 2015

### ISSUE THREAD

**Issue by dkdndes** [sqlanywhere/sqlany-django#9]
Support for Django 1.6.11 ended April 2015

Please, have a look [here](https://docs.djangoproject.com/en/dev/internals/release-process/#supported-versions) and [here](https://www.djangoproject.com/download/). Search for LTS.

**Comment by gperrow-SAP** [comment]
Version 1.11 of the driver was just uploaded, which includes support for Django 1.8.
